#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "pico/stdlib.h"
#include "hardware/gpio.h"

#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "lab09.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to
#define RGB_BLUE 0      // Parameter to pass to set_rgb_led to change LED colour to blue.
#define RGB_GREEN 1     // Parameter to pass to set_rgb_led to change LED colour to green.
#define RGB_RED 2       // Parameter to pass to set_rgb_led to change LED colour to red.
#define RGB_ORANGE 3    // Parameter to pass to set_rgb_led to change LED colour to orange.
#define RGB_PINK 4		// Parameter to pass to set_rgb_led to change LED colour to pink.
#define RGB_OFF 5       // Parameter to pass to set_rgb_led to turn the RGB LED off.

// Declare the main assembly code entry point.
void main_asm();

// Initialise a GPIO pin – see SDK for detail on gpio_init()
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Set direction of a GPIO pin – see SDK for detail on gpio_set_dir()
void asm_gpio_set_dir(uint pin, bool out) {
    gpio_set_dir(pin, out);
}

// Get the value of a GPIO pin – see SDK for detail on gpio_get()
bool asm_gpio_get(uint pin) {
    return gpio_get(pin);
}

// Set the value of a GPIO pin – see SDK for detail on gpio_put()
void asm_gpio_put(uint pin, bool value) {
    gpio_put(pin, value);
}

// Enable falling-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
}

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

/**
 * @brief   		Function to set the colour of the RGB LED on the Pi Pico 
 *          		given a colour parameter, or to turn the RGB LED off.
 * 
 * @param colour    An integer value corresponding to a set colour used by the program.
 */
void set_rgb_led(int colour) {

    // Switch statement below checks what parameter has been passed and sets the RGB LED to the desired colour/state.
    switch(colour) {
        case RGB_GREEN:
            // Set the colour to GREEN.
            put_pixel(urgb_u32(0x00, 0x7F, 0x00));
            break;

        case RGB_RED:
            // Set the colour to RED.
            put_pixel(urgb_u32(0x7F, 0x00, 0x00));
            break;

        case RGB_ORANGE:
            // Set the colour to ORANGE.
            put_pixel(urgb_u32(0x99, 0x4C, 0x00));
            break;
    }
}

void main_asm();
void asm_adc_init();
void asm_adc_select_input(int AINSEL_num);
uint16_t asm_adc_read();
void asm_adc_set_temp_sensor_enabled(bool enable);

/**
 * @brief Function that converts the parameter raw_temp which is in hex (11 bits) to celsius 
 *        by calculating the appropriate conversion_factor and calculating the ADC_voltage and then answer as celsius
 * 
 * @param raw_temp 11 bits of RESULT of ADC_BASE #0x04 offset. Hex 
 * @return float answer in celsius given param
 */
float asm_convert_raw_temp_to_celsius(uint16_t raw_temp) {
    const float conversion_factor = 3.3f / (1 << 12);
    float answer = 27 - ( ( (raw_temp * conversion_factor) - 0.706) / 0.001721 ); // Temperature approximation
    // T = 27 - (ADC_voltage - 0.706)/0.001721 
    printf("The Temperature is %f degrees Celsius\n", answer);
    if (answer >= 25) { // if degrees 25 or more
        set_rgb_led(RGB_RED); // red for hot
    }
    else if (answer >= 24) { // if degrees 24 or more
        set_rgb_led(RGB_ORANGE); // green for medium
    }
    else { // else degrees cool
        set_rgb_led(RGB_GREEN); // green for cool
    }
    return answer;
}

// Main entry point of the application
int main() {
    stdio_init_all();              // Initialise all basic IO
    printf("Lab #9...\n");         // Basic print to console
    PIO pio = pio0; // Initialise rgb led 
    uint offset = pio_add_program(pio, &ws2812_program); 
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);

    main_asm();

    return 0;                      // Application return code
}